### ISSUE TITLE
Assignment 2 is ready for grading

### ISSUE THREAD

**Issue by mwillisj** [SES-5215-F2020/mwillisjackson-quant#2]
Looking forward to your feedback!

**Comment by mwillisj** [comment]
https://ses-5215-f2020.github.io/mwillisjackson-quant/Assignment2.html

**Comment by c-voulgaris** [comment]
This looks great. Nice job on the text interpretations.

Detailed comments on code:
Line 15: I would suggest breaking this into separate code chunks. One to load the libraries, one to load the data and one to do the calculations, for example. And I'd probably combine the t-test chunk with the one where you calculate all the other descriptive statistics. 

Lines 21 - 37: This is a little confusing to read. A simpler and more readable way to do what you're doing would be to use the `tibble()` function:

```
summary_stats_contvar <- tibble(variables = c("Travel_Time","Household_Income","Housing_Cost"),
       median  = c(median(person_data$travel_time), 
                           median(person_data$household_income), 
                           median(person_data$monthly_housing_total)),
       standard_deviation = c(sd(person_data$travel_time),
                                             sd(person_data$household_income),
                                             sd(person_data$monthly_housing_total)),
       low_CI_95 = c(t.test(person_data$travel_time)[["conf.int"]][1],
                            t.test(person_data$household_income)[["conf.int"]][1],
                            t.test(person_data$monthly_housing_total)[["conf.int"]][1]),
       high_CI_95 = c(t.test(person_data$travel_time)[["conf.int"]][2],
                            t.test(person_data$household_income)[["conf.int"]][2],
                            t.test(person_data$monthly_housing_total)[["conf.int"]][2]),
       IQ_Range = c(IQR(person_data$travel_time),
                             IQR(person_data$household_income),
                             IQR(person_data$monthly_housing_total)))
```

Also - if you include the table you created with that code, you don't need to also print the descriptive statistics on the histograms. Or if you do, you don't need to create these tables.

Also on the topic of code readability - try to avoid lines that are longer than 80 characters long - if you have a function with a lot of arguments, you can always put each argument on its own line. And add spaces between lines unless they are really closely related.

Lines 370 and 385: If you intended to set the colors of the bars to red/purple, rather than just their outlines, use "fill" rather than "color".
